# QApp/Dockerfile
FROM python:3.11-slim
 
WORKDIR /app
ENV PYTHONPATH=/app
 
COPY Frontend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
 
COPY . .
 
EXPOSE 8501
 
CMD ["streamlit", "run", "Frontend/streamlit_app.py", "--server.address=0.0.0.0", "--server.port=8501"]
